### ISSUE TITLE
why not code hinting while use Then

### ISSUE THREAD

**Issue by zixun** [devxoul/Then#14]
why not code hinting by xcode while use Then

**Comment by devxoul** [comment]
I think Xcode is silly.

**Comment by KimDarren** [comment]
:+1: to this issue..
Is there any great solution instead of memorizing the code?

**Comment by kos9kus** [comment]
"I think Xcode is silly." sounds like a pun =) 
Anyway, it's real downside while using this terrific lib.
Could it have some workarounds or tricks ?

**Comment by PabloLerma** [comment]
You can create your own code snippet like this:

![screen shot 2016-08-10 at 21 25 42](https://cloud.githubusercontent.com/assets/871250/17567789/1a24a16a-5f41-11e6-96ad-285a15e6a45a.png)

**Comment by jedmund** [comment]
If people are having the same issue as me, I think the concern is more with writing properties inside of the Then block, not necessarily the syntax of the Then block.

In that case, no, I don't think there's anything that can be done, but I'd love to be proven wrong!

**Comment by devxoul** [comment]
I created an issue on Swift JIRA: https://bugs.swift.org/browse/SR-2750 (please vote on JIRA issue!)

**Comment by Natai** [comment]
@devxoul I created a label with Then, I found that Xcode will hint if the label is a local variable，but Xcode will not if the label is a property. What happend...

**Comment by devxoul** [comment]
@Natai yeah, thanks to @txaiwieser (#38) we found that code hinting is ~~now~~ not working in class scope.

**Comment by jackhub** [comment]
still not working if the label is a property

**Comment by devxoul** [comment]
Oh my god, there was a mistypo: ~~now working~~ -> not working
Sorry for confusing 😅

**Comment by bobleesj** [comment]
## Collaboration Needed

If you want to use auto-completion, please visit [Swift Bug](https://bugs.swift.org/browse/SR-2750) and upvote. Good for both of us.

**Comment by acecilia** [comment]
Still not autocompleting with the new xCode :(

**Comment by LeeBigRay** [comment]
I tried all of what you say ,but it did not been solved

**Comment by bobleesj** [comment]
Life is tough.

**Comment by KimDarren** [comment]
Since Xcode 9 and Swift 4, the auto-completion is working well for me.

**Comment by acecilia** [comment]
As @KimDarren said, with xCode 9.1 (9B55) and Swift 4, autocompletion is working at class level for me. Yay!! @devxoul your issue (https://bugs.swift.org/browse/SR-2750) is still open though.

![captura de pantalla 2017-12-05 a las 18 23 32](https://user-images.githubusercontent.com/7938671/33602169-7a7df7f4-d9e9-11e7-9f95-f6f9d0ee8fdb.png)

**Comment by devxoul** [comment]
@KimDarren @acecilia, have you tested using Then?

**Comment by acecilia** [comment]
Not yet

**Comment by KimDarren** [comment]
Not yet too

**Comment by acecilia** [comment]
@devxoul just did. Seems to be working:
![captura de pantalla 2017-12-06 a las 16 27 00](https://user-images.githubusercontent.com/7938671/33651976-9dcdcf36-daa2-11e7-8005-02a81fa06e74.png)

**Comment by devxoul** [comment]
I've found an interesting thing. It works without  a type annotation and it doesn't work with a type annotation(`: UILabel`).

**With type annotation**

<img width="411" alt="screen shot 2018-01-11 at 4 13 16 am" src="https://user-images.githubusercontent.com/931655/34790692-e0f84846-f685-11e7-950c-fbece30f5f27.png">

**Without type annotation**

<img width="398" alt="screen shot 2018-01-11 at 4 13 23 am" src="https://user-images.githubusercontent.com/931655/34790697-e80f59da-f685-11e7-9801-3c15faf3ce9e.png">

**Comment by acecilia** [comment]
Further discussion here: https://bugs.swift.org/browse/SR-2750

**Comment by devxoul** [comment]
This is fixed in Xcode 11.
