### ISSUE TITLE
Strange issue after updating to version 1.0.0

### ISSUE THREAD

**Issue by tuyendv2** [devxoul/Then#19]
I got compiling error **Cannot convert value of type '_ -> ()' to expected argument type 'inout WKWebView -> Void'** with this code

```
webView.then {
    $0.navigationDelegate = self
}
```

However, the error's gone when there are two assignments in the block

```
webView.then {
    $0.navigationDelegate = self
    $0.tag = 1
}
```

**Comment by devxoul** [comment]
Hi @tuyencoder, it seems to be an Xcode issue.

[Possible workaround](https://github.com/devxoul/Then#trouble-shooting) is to put `return`. 

``` swift
webView.then {
    $0.navigationDelegate = self
    return
}
```

**Comment by tuyendv2** [comment]
It works now. Thank you!

**Comment by devxoul** [comment]
:smile:
