### ISSUE TITLE
Doesn't work with UIView subclasses after Xcode 7.3.1 update

### ISSUE THREAD

**Issue by fnc12** [devxoul/Then#23]
...but works fine with CALayer, NSAttributesString subclasses

**Comment by devxoul** [comment]
@fnc12, can you please attach the code?

**Comment by 1amageek** [comment]
Value of type 'UIImageView' has no member 'then'

```
    private(set) lazy var imageView: UIImageView = {
        return UIImageView(frame: .zero).then {
            $0.contentMode = .ScaleAspectFill
            $0.clipsToBounds = true
        }
    }()

```

**Comment by devxoul** [comment]
@fnc12, Which version of Then are you using? If it is lastest version, could you please make a new project and try again?

**Comment by devxoul** [comment]
@1amageek Did you import `Then` correctly?

``` swift
import Then

class MyClass {

    private(set) lazy var imageView: UIImageView = {
        return UIImageView(frame: .zero).then {
            $0.contentMode = .ScaleAspectFill
            $0.clipsToBounds = true
        }
    }()

}
```

**Comment by philipengberg** [comment]
I can confirm that this no longer works as of Xcode `7.3.1`

**Comment by philipengberg** [comment]
Turns out this destroys everything:

``` swift
extension NSObject : Then {}
```

If you instead do this:

``` swift
extension UIView : Then {}
```

it works fine ¯\_(ツ)_/¯ - for views only, obviously.
It requires you to add the extension to every topmost type below `NSObject`, where you want to use `then`.

**Comment by devxoul** [comment]
@philipengberg, That's odd. Because my project has no problem at all. Even if I made a new project. Have you tested with a new project?

I'll try to find a solution as soon as possible.

**Comment by fnc12** [comment]
This is very odd. I have three actual projects right now and two of them show me error with my UIView subclasses but one of them compiles ok

**Comment by devxoul** [comment]
@fnc12, can you guess what the difference between the projects is?

**Comment by irace** [comment]
I opened a Swift bug for this: https://bugs.swift.org/browse/SR-1480

**Comment by BasThomas** [comment]
Seems this has been fixed: https://github.com/apple/swift/pull/2565
