### ISSUE TITLE
Accessing instance variables in then block

### ISSUE THREAD

**Issue by AndrewSB** [devxoul/Then#30]
I can't seem to access class variables in my then block:

For example

```
class GradientView {
   let colors = ...
   lazy var gradientLayer = CAGradientLayer().then {
       $0.colors = self.colors // also tried colors
   }
}
```

doesn't work, but 

```
class GradientView {
   let colors = ...
   lazy var gradientLayer: CAGradientLayer = {
       let layer = CAGradientLayer()
       layer.colors = self.colors
       return layer
   }()
}
```

does.

Can I repeat my old pattern of accessing instance variables in a lazy init using Then?

**Comment by devxoul** [comment]
@AndrewSB, sorry for delay! It seems like a Swift bug. Adding type annotation to `gradientLayer` might work :)

<pre>
class GradientView {
   let colors = ...
   lazy var gradientLayer<strong>: CAGradientLayer</strong> = CAGradientLayer().then {
       $0.colors = self.colors // also tried colors
   }
}
</pre>

<img width="518" alt="screen shot 2016-08-01 at 6 30 22 pm" src="https://cloud.githubusercontent.com/assets/931655/17289766/0d367672-5816-11e6-8fa9-29b99a31bb7f.png">

**Comment by devxoul** [comment]
@AndrewSB, Doesn't it work?

**Comment by AndrewSB** [comment]
It does! Thanks @devxoul!
