### ISSUE TITLE
cannot install through carthage

### ISSUE THREAD

**Issue by ghost** [devxoul/Then#31]
> **\* Skipped building Then due to the error:
> Dependency "Then" has no shared framework schemes

Please follow this guide to fix -> https://github.com/Carthage/Carthage#share-your-xcode-schemes

**Comment by devxoul** [comment]
@danjiang, how did you configure your **`Cartfile`**? Then is compatible with Carthage.

``` console
$ cat Cartfile
github "devxoul/Then" ~> 1.0
$ carthage version
0.17.1
$ carthage update
*** Fetching Then
*** Checking out Then at "1.0.3"
*** xcodebuild output can be found in /var/folders/yk/ms2yrh7s2_g26y4rh4n9mpww0000gn/T/carthage-xcodebuild.cTjuK0.log
*** Building scheme "Then-OSX" in Then.xcodeproj
*** Building scheme "Then-tvOS" in Then.xcodeproj
*** Building scheme "Then-iOS" in Then.xcodeproj
```

**Comment by ghost** [comment]
@devxoul, but it is also checkout 1.0.3

`github "devxoul/Then"`

**Comment by devxoul** [comment]
Which platform are you building?

**Comment by ghost** [comment]
iOS. I run following `carthage build --platform ios`

**Comment by devxoul** [comment]
This is odd. There're shared schemes as you can see here: https://github.com/devxoul/Then/tree/1.0.3/Then.xcodeproj/xcshareddata/xcschemes

And even Carthage build is working on my machine :(

**Comment by ghost** [comment]
The Carthage Checkouts is checkout from my teammate`s git repo. Maybe there is problem when he add it. I will clean and checkout from https://github.com/devxoul/Then to see if it still have this problem.

**Comment by devxoul** [comment]
If that doesn't work, try

``` console
$ rm -rf ~/Library/Caches/org.carthage.CarthageKit/dependencies/Then
```

and build again.

**Comment by ghost** [comment]
I clean and update build, everything is fine. I close this issue.
