### ISSUE TITLE
How to use 'do' block?

### ISSUE THREAD

**Issue by zbangsatz** [devxoul/Then#36]
First think I want to say: Thank you! It's awesome.

My trouble is can't use 'do' block. The compile show error "Expected member name following.". Example:

NSUserDefaults.standardUserDefaults().do({
           // Do anything with UserDefaults
})

**Comment by devxoul** [comment]
@zbangsatz It's because `do` is reserved keyword in Swift 2. In order to use `do` in Swift 2 project, you should use backtick(`).

``` swift
NSUserDefaults.standardUserDefaults().`do` {
  $0.synchronize()
}
```
