### ISSUE TITLE
cocoapods with 'Then' issues

### ISSUE THREAD

**Issue by yanjinquan** [devxoul/Then#40]
when I use it with cocoapods ,I will get the issues "Command /bin/sh failed with exit code 1", but not
appear  other what like "then".it is my pods file:

> platform :ios, '9.0'
> use_frameworks!
> 
> target 'MapInSwift' do
>     pod 'Alamofire'
>     pod 'SwiftyJSON'
>     pod 'Then', '~> 2.1'
> end

if i remove the line with "pod 'Then', '~> 2.1'", i will get no issue

I fand the solution on the google but no way is fit me.If i need particular setting with Xcode(xcode 8.0; swift 3.0)

**Comment by devxoul** [comment]
@yanjinquan, try:

```
$ pod repo update
$ pod install
```

If it doesn't work, could you please provide me a detailed error message?

**Comment by yanjinquan** [comment]
thanks for your help. I have solved this question.
by update my cocoapods version to 1.1.1,    add "Xcode build Setting -> Other Linker Flags" "$(inherited)",  and deleted the "Xcode/DerivedData/Build/Products/Debug-iphonesimulator/xxxxxx.app/Frameworks" file

**Comment by devxoul** [comment]
Sounds great :)
