### ISSUE TITLE
Don't push a new branch

### ISSUE THREAD

**Issue by vilapuigvila** [devxoul/Then#42]
Hi everyone!
I'd like to contribute to this repo and today I've not been able to push my branch, I got this message:
remote: Permission to goktugyil/EZSwiftExtensions.git denied to vilapuigvila.
fatal: unable to access 'https://github.com/goktugyil/EZSwiftExtensions.git/': The requested URL returned error: 403
Thanks in advance.

**Comment by devxoul** [comment]
@vilapuigvila 
1. If you want to contribute the code, you have to make a [pull request](https://help.github.com/articles/about-pull-requests/).
2. Why are you asking about EZSwiftExtensions here?

**Comment by vilapuigvila** [comment]
I must apologize, I wanted write in the EZSE forum. You can close this issue.
Regards.
