### ISSUE TITLE
@noescape

### ISSUE THREAD

**Issue by onmyway133** [devxoul/Then#5]
Hi, I just make my [Configurable](https://github.com/onmyway133/Configurable) and realize you're 1 step before me :smile: 

I see that this pattern is now widely adopted in many projects, like [Dip](https://github.com/AliSoftware/Dip), ... for the compensation of Builder pattern. Like Dip, I have `Initable` which works on `init` as well, good for basic usage

One thing you can improve is to leverage `@noescape` http://nshint.io/blog/2015/10/23/noescape-attribute/

**Comment by devxoul** [comment]
@onmyway133, thank you for pointing it out!
There is already a PR for making closure non-escapable. (#1)
This will be shipped in next release.
