### ISSUE TITLE
doesn't support watchOS 3 or 4

### ISSUE THREAD

**Issue by sheng168** [devxoul/Then#51]

**Comment by devxoul** [comment]
What did you mean?

**Comment by sheng168** [comment]
adding this to watchOS project using cocoapods fails

**Comment by devxoul** [comment]
Which error message did you get?

**Comment by sheng168** [comment]
Analyzing dependencies
[!] The platform of the target `BabyTime WatchKit Extension` (watchOS 3.0) is not compatible with `Then (2.1.0)`, which does not support `watchos`.

**Comment by devxoul** [comment]
Oh, sorry. I forgot to release a new version after [adding watchOS support](https://github.com/devxoul/Then/commit/9995c1e001800e1aaaf11982fd10c2c68e159fde). I just released [2.1.1](https://github.com/devxoul/Then/releases/tag/2.1.1) and this will probably work.

```console
$ pod repo update
$ pod install
```

**Comment by sheng168** [comment]
thanks
