### ISSUE TITLE
ERROR when upload to AppStore

### ISSUE THREAD

**Issue by devjia** [devxoul/Then#56]
ERROR ITMS-90056: "This bundle Payload/X.app/Frameworks/Then.framework is invalid. The Info.plist file is missing the required key: CFBundleVersion."

**Comment by devxoul** [comment]
@devjia, I updated the prebuilt binary. Could you please try again?

```console
$ carthage update
```

**Comment by devjia** [comment]
Thanks!
I solved this issue by manually modify the info.plist file of Then.framework.

And, the new prebuilt binary looks no problem. 

But,
`carthage update` will broken and throws `Incompatible Swift version - framework was built with 4.0 (swiftlang-900.0.65.2 clang-900.0.37) and the local version is 4.0 (swiftlang-900.0.65 clang-900.0.37).`
I think I should update Xcode to version 9.0.1 to solve this.

Is there a way not use prebuilt binary ? 
Do you have any suggestion?

**Comment by devxoul** [comment]
I suggest you to update Xcode to 9.0.1.

**Comment by devjia** [comment]
Thanks!
