### ISSUE TITLE
UICollectionView doesn't show cells

### ISSUE THREAD

**Issue by TaeJoongYoon** [devxoul/Then#63]
<img width="679" alt="image" src="https://user-images.githubusercontent.com/24986688/45926002-34956280-bf59-11e8-8740-f133a151babb.png">

If I create a UICollectionView with upside code, it works good.
However, I create UICollectionView with downside code, it doesn`t show cells.
Others code all same.

What's the problem??

**Comment by devxoul** [comment]
You have to use `UICollectionView`'s designated initializer.

```swift
let collectionView = UICollectionView(frame: .zero, collectionViewLayout: UICollectionViewFlowLayout()).then {
  $0.translatesAutoresizingMaskIntoConstraints = false
  $0.register(Reusable.flickrCell)
}
```

**Comment by TaeJoongYoon** [comment]
Thank you!

I did it like your code... but it was not working...

It's nice now, I don't know why 😂😂 perhaps it's my fault.
