### ISSUE TITLE
lazy code

### ISSUE THREAD

**Issue by hanks-hu** [devxoul/Then#64]
lazy var tableView: UITableView = {
        let tabView =UITableView.init(frame: .zero, style: .plain)
        tabView.backgroundColor = UIColor.white
        tabView.dataSource = self
        tabView.delegate = self
        return tabView
    }()
I often use lazy loading， and，how to write by Then。Can you give me a test code。

**Comment by devxoul** [comment]
Doesn't it work?

```swift
lazy var tableView = UITableView(frame: .zero, style: .plain).then {
  $0.backgroundColor = UIColor.white
  $0.dataSource = self
  $0.delegate = self
}
```

**Comment by hanks-hu** [comment]
😂，sorry，It's my problem。But, I found another problem。Code hinting。
Xcode Version 10.1 (10B61)。
<img width="648" alt="2018-11-02 5 12 36" src="https://user-images.githubusercontent.com/16836336/47906012-4dcbf000-dec3-11e8-91fe-78eb7f4a8677.png">
<img width="953" alt="2018-11-02 5 13 26" src="https://user-images.githubusercontent.com/16836336/47906018-4efd1d00-dec3-11e8-9499-79757fb3a1cc.png">

**Comment by SeRG1k17** [comment]
@devxoul Hi, sorry to bother you. Any updates about Carthage support?

**Comment by iTofu** [comment]
@HanksHu 
did your Xcode give you the hint now?

**Comment by hanks-hu** [comment]
@iTofu        sorry. 
use `let`, give me  hints.
```swift
let orderNumLabel = UILabel().then {
}
```
but，use` lazy var`, Don't  give me  hints.
``` swift
 lazy var orderNumLabel = UILabel().then {
        $0.textColor = UIColor.init(hex: "b7b7b7")
        $0.numberOfLines = 1
        
    }
```

**Comment by iTofu** [comment]
@HanksHu 
fine and thank you :(

**Comment by WannaYoung** [comment]
@HanksHu 
me too
use `let`, give me hints. use` lazy var`, Don't give me hints.
