### ISSUE TITLE
No code prompt in Xcode 10.2

### ISSUE THREAD

**Issue by monologue555** [devxoul/Then#67]
![image](https://user-images.githubusercontent.com/23382969/55081864-93d85900-50db-11e9-934a-ab2ebbbe1bbd.png)

**Comment by devmjun** [comment]
I have same issues😭

**Comment by yyyear** [comment]
I have same issues😭

**Comment by yyyear** [comment]
I have same issues

**Comment by shengwanlin** [comment]
+1

**Comment by WannaYoung** [comment]
+10086

**Comment by WannaYoung** [comment]
<img width="472" alt="屏幕快照 2019-04-19 下午7 09 35" src="https://user-images.githubusercontent.com/5809002/56421767-be7e9180-62d6-11e9-90c4-e5e2ea07b244.png">

**Comment by ZikeX** [comment]
<img width="509" alt="image" src="https://user-images.githubusercontent.com/24931121/56716648-75628d80-676d-11e9-873c-c4a1737567fb.png">

**Comment by summerthread** [comment]
+1

**Comment by benedekvarga** [comment]
+1

**Comment by jw10126121** [comment]
+1

**Comment by VincentSit** [comment]
Is this issue fixed in Xcode 11?

**Comment by VincentSit** [comment]
It has been confirmed that Xcode 11.0 beta (11M336w) fixes the issue. :smiley:
 
![image](https://user-images.githubusercontent.com/4084679/59105458-84408080-8966-11e9-829b-c8eb0a452ab4.png)

**Comment by status302** [comment]
+1 Xcode10.3

**Comment by devxoul** [comment]
It seems that it is fixed in Xcode 11.
