### ISSUE TITLE
Suggestion: Then? Why not With?

### ISSUE THREAD

**Issue by mattijsf** [devxoul/Then#7]
Nice idea!

I personally suggest a different keyword: `.with { ... }`

``` swift
UILabel().with {
    $0.textColor = .blackColor() 
} 
```

Makes a bit more sense.

The keword/idea reminds me a bit of the old VB's `With...End With` statement: https://msdn.microsoft.com/en-us/library/wc500chb.aspx

**Comment by devxoul** [comment]
Hi @mattijsf!
Why I chose `then` instead of `with` is to avoid name conflicts. Because `with()` is more general than `then()`. That means, other frameworks might have `with()` already.

**Comment by mattijsf** [comment]
Okay! Sounds like you already gave it a thought :)
