### ISSUE TITLE
add @discardableResult 

### ISSUE THREAD

**Issue by biancheng347** [devxoul/Then#79]
_ = UIView().then {
    $0.tag = 1
}

--------

UIView().then {
    $0.tag = 1
}

如果是下面的，有很多警告

**Comment by carlos-chaguendo** [comment]
Use

```
UIView().do {
$0.tag = 1
}
```

**Comment by weixianlove** [comment]
.then 是有返回值的，你不使用返回值，xcode自身会有警告
使用下划线可以忽略
.do 本身就没有返回值，所以不需要返回值的话你可以直接使用.do

**Comment by devxoul** [comment]
You may use `do()` instead.
