### ISSUE TITLE
iOS 14 Deployment Target Warning 

### ISSUE THREAD

**Issue by berbschloe** [devxoul/Then#84]
In the new Xcode (12) there is a SwiftPM import warning.

![Screen Shot 2020-10-14 at 1 58 19 PM](https://user-images.githubusercontent.com/5903560/96033148-581ff400-0e25-11eb-89b6-caeb3272f82c.png)

In order to fix I think all you have todo is bump the version to iOS 9 in the `Package.swift` file.
If you are wanting to maintain backwards support I think you can make a new `Package@swift-5.3.swift`

[KeychainAccess](https://github.com/kishikawakatsumi/KeychainAccess) did something similar.

**Comment by RomanPodymov** [comment]
The issue can be closed.
