### ISSUE TITLE
Xcode 14 code prompt error

### ISSUE THREAD

**Issue by whisterlee** [devxoul/Then#96]
Use Then with Xcode14, and the code prompts that there is something wrong.
![WechatIMG226](https://user-images.githubusercontent.com/17923550/197919587-7c5e0db9-d6fd-4cd1-926a-ce1d027de9f9.png)

**Comment by yisRookie** [comment]
I have the same problem~

**Comment by yisRookie** [comment]
![截屏2022-10-26 17 26 43](https://user-images.githubusercontent.com/5171627/197991155-a2285100-4298-4788-b2ef-fcd3b79f5086.png)

**Comment by yisRookie** [comment]
Like the issue  #71

**Comment by loinsir** [comment]
I have same issue

**Comment by JJIKKYU** [comment]
저도 같은 이슈가 있습니다.
xcode14 이후로 첫 라인을 제외한 두번째 라인부터 $0에 대한 타입 추론을 하지 못하는 것 같습니다.

**Comment by loinsir** [comment]
@JJIKKYU 저는 해결된것 같습니다. 혹시 확인 가능하신가요?

**Comment by WhiteHyun** [comment]
Specifying the type of a variable can resolve this issue.
For example:

|Type Annotation| Type Inferred|
|:-:|:-:|
|<img width="424" alt="image" src="https://user-images.githubusercontent.com/57972338/210038313-606c2af2-9054-4cc5-bf0a-9e80994e3586.png">|<img width="415" alt="image" src="https://user-images.githubusercontent.com/57972338/210038339-b579227b-46d1-4f85-b199-5477b034ef98.png">|

Specifying the type of the parameter inside the closure is also possible.

|Closure type annotation|
|:-:|
|<img width="563" alt="image" src="https://user-images.githubusercontent.com/57972338/210038279-ca0cb80d-75ee-44f6-8627-4064f145122e.png">|

**Comment by loinsir** [comment]
Then 내부 코드의 @inlinable 애트리뷰트의 컴파일러 내부 동작에 뭔가 변화가 있어서 이런일이 발생한것 같은데요, 실제로 @inlinable 대신 @inline(__always) 등으로 교체해서 적용해보니 동작했던것 같습니다. 혹시 확인 가능하신가요? @WhiteHyun

**Comment by WhiteHyun** [comment]
음 저는 안되는 것 같네요. 😭
@loinsir

**Comment by make1a** [comment]
I have the same issue 
![image](https://github.com/devxoul/Then/assets/17469549/6e348a2e-1be7-4946-93b5-2ecaa6b4e4f3)

**Comment by pengzishangTest** [comment]
Keep editing in the first line when XCode. The completion will load fine.

**Comment by whisterlee** [comment]
The issue has been resolved in Xcode 15.
